#!/bin/bash

cd /home/adrian/backup
#gzip -d back_nuevo.tar.gz
#tar -xvf back_nuevo.tar

# no descomentar la sigte. linea
#pg_restore -i -h localhost -p 5432 -U postgres -d BENEF -v "/home/adrian/backup/MENU.backup"

#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/ACTIVIDAD_CATEGORIA.dump" 
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/ACTIVIDAD_COBERTURA.dump"
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/AJUSTE_TARIFA_PROD.dump"
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/AJUSTE_TARIFA_ZONA.dump" 
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/ALERTAS.dump"
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/BANCOS.dump"
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/BONIFICACION.dump"
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/BONIFICACION_ABM.dump"
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/COBERTURAS.dump"
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/CODIGOS.dump"
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/COND_FACTURACION.dump"
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/COMISIONES.dump"
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/COT_COTIZACIONES.dump"
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/C_ASEGURADO.dump"
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/C_ASEG_BENEF.dump"
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/C_ASEG_COB.dump"
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/C_CERTIFICADO.dump"
pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/C_COB_SUMAS.dump"
pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/C_TEXTO_FIJO.dump"
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/C_TEXTO_VAR.dump"
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/C_TOMADOR.dump"
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/C_CLAUSULA_BENEF.dump" 
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/ERROR.dump" 
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/ESTADOS.dump" 
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/IMPUESTOS.dump"
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/IMPUESTOS_ABM.dump" 
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/INTERFASES.dump" 
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/INTERFASE_MANUAL.dump" 
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/MAIL.dump"
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/MANUALES.dump" 
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/MENU.dump"
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/MONEDAS.dump"
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/NOVEDADES.dump"
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/OPCION_AJUSTE.dump" 
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/OPCION_AJUSTE_DET.dump" 
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/ORGANIZADORES.dump" 
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/PERSONAS.dump"
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/PLAN.dump" 
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/PLAN_COSTO.dump"
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/PLAN_PRODUCTOR.dump"
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/PLAN_SUMAS.dump" 
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/PROCEDENCIAS.dump" 
pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/PRODUCTOS.dump" 
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/PRODUCTOR_COBERTURA.dump" 
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/PRODUCTOR_POR_ORG.dump" 
pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/PRODUCTOR_SETEOS.dump" 
pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/PRODUCTOR_CUOTAS.dump" 
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/PRUEBAS.dump" 
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/RAMAS.dump"
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/SUB_RAMAS.dump"
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/S_ASEGURADO.dump" 
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/S_COBERTURAS.dump" 
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/S_ERRORES.dump"
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/S_PROPUESTA.dump"
pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/S_TOMADOR.dump" 
pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/S_UBICACION_RIESGO.dump" 
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/S_CLAUSULA_BENEF.dump" 
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/TABLAS.dump" 
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/TARJETAS.dump" 
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/TASA_MENSUAL.dump"
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/TASA_MENSUAL_ABM.dump"
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/TASA_PROVINCIAL.dump"
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/TASA_PROVINCIAL_ABM.dump" 
pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/TIPOS_FORMA_PAGO.dump" 
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/TIPOS_MOVIMIENTO.dump" 
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/TRAMO.dump" 
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/TRAMO_ABM.dump"
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/USUARIOS.dump"
#pg_restore -i -h localhost -p 5432 -W -U postgres -d BENEF -v "/home/adrian/backup/VIGENCIA.dump"

#para restaurar gzip -d fichero.gz   tar -xvf archivo.tar
#psql -h 127.0.0.1 -f benef.PRUEBAS.dump BENEF postgres
